import { text } from "express";
import gemiAI from "../config/geminiAI.js";
import openai from "../config/openAI.js";
import ChatModel from "../models/chatModel.js";

// Text generated by AI Controller
// export const textMessageController = async (req, res) => {
//   try {
//     const { chatId, prompt } = req.body;
//     if (!chatId || !prompt) {
//       return res.json({ success: false, message: "Invalid Data" });
//     }

//     // Load chat and history
//     const chat = await ChatModel.findById(chatId);

//     if (!chat) {
//       return res.json({ success: false, message: "Chat not found" });
//     }

//     // Add new user message to history
//     chat.message.push({
//       role: "user",
//       content: prompt,
//       timestamp: Date.now(),
//       isImage: false,
//     });

//     // Format history for Gemini API (role: "model" for AI, "user" for user)
//     const messages = chat.message.map((msg) => ({
//       role: msg.role === "assistant" ? "model" : msg.role,
//       content: msg.content,
//     }));
//     // Call Gemini API with full message history
//     const { choices } = await openai.chat.completions.create({
//       //choices because gemini returns choices array
//       model: "gemini-2.0-flash",
//       history:messages,
//       messages: [
//         {
//           role: "user",
//           content: prompt,
//         },
//       ],
//     });

//     const reply = {
//       ...choices[0].message,
//       timestamp: Date.now(),
//       isImage: false,
//     }; //destructuring the message from choices array
//     res.json({ success: true, message: "Message added", reply });
//     chat.message.push(reply);
//     chat.save();
//   } catch (error) {
//     res.json({ success: false, message: error.message });
//   }
// };

export const textMessageController = async (req, res) => {
  try {
    const { chatId, prompt } = req.body;
    if (!chatId || !prompt) {
      return res.json({ success: false, message: "Invalid Data" });
    }
    // Load chat and history
    const chat = await ChatModel.findById(chatId);
    const history = chat.message.map((msg) => ({
      role: msg.role === "assistant" ? "model" : msg.role,
      parts:[{text: msg.parts[0].text,}]
    }));
    if (!chat) {
      return res.json({ success: false, message: "Chat not found" });
    }
    chat.message.push({
      role: "user",
      parts: [{ text: prompt }],
      timestamp: Date.now(),
    });

    const aiChat = gemiAI.chats.create({
      model: "gemini-2.0-flash",
      history: history,
    });
    const reponseAi = await aiChat.sendMessage({ message: prompt });
    res.json({
      success: true,
      message: "Message added",
      reply: reponseAi.text,
    });
    chat.message.push({
      role: "model",
      parts: [{ text: reponseAi.text }],
      timestamp: Date.now(),
    });
    chat.save();
  } catch (error) {
    res.json({ success: false, message: error.message });
  }
};
