import openai from "../config/openAI.js";
import ChatModel from "../models/chatModel.js";

// Text generated by AI Controller
export const textMessageController = async (req, res) => {
  try {
    const { chatId, prompt } = req.body;
    if (!chatId || !prompt)
      return res.json({ success: false, message: "Invalid Data" });
    const chat = await ChatModel.findById(chatId);
    chat.message.push({
      role: "user",
      content: prompt,
      timestamp: Date.now(),
      isImage: false,
    });
    const { choices } = await openai.chat.completions.create({
      //choices because gemini returns choices array
      model: "gemini-2.0-flash",
      messages: [
        {
          role: "user",
          content: prompt,
        },
      ],
    });

    const reply = {
      ...choices[0].message,
      timestamp: Date.now(),
      isImage: false,
    }; //destructuring the message from choices array
    res.json({ success: true, message: "Message added", reply });
    chat.message.push(reply);
    chat.save();
  } catch (error) {
    res.json({ success: false, message: error.message });
  }
};
